name: On-Premises-Data-Gateway-Versions-Release

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Release
      run: |
      
        # Download Standard Data Gateway 
        $standardFileName = "GatewayInstall_Standard.exe"
        Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?LinkId=2116849 -OutFile $standardFileName
        $version = $((Get-Item $standardFileName).VersionInfo.ProductVersion)

        # Download Personal Mode Data Gateway
        $personalFileName = "GatewayInstall_Personal.exe"
        Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?LinkId=2116848 -OutFile $personalFileName    
        
        # Create GitHub Release
        $token = "${{ secrets.GITHUB_TOKEN }}"
        $apiUrl = "https://api.github.com/repos/apchevski/On-Premises-Data-Gateway-Versions/releases"
        $tag = "v$version"
        
        $headers = @{
            "Accept" = "application/vnd.github+json"
            "Authorization" = "Bearer $token"
            "X-GitHub-Api-Version" = "2022-11-28"
        }

        $body = @{
            tag_name = "$tag"
            target_commitish = "main"
            name = "$version"
            body = ""
            draft = $false
            prerelease = $false
            generate_release_notes = $false
        } | ConvertTo-Json
        
        $response = Invoke-RestMethod -Uri $apiUrl -Method Post -Headers $headers -Body $body
        $releaseId = $response.id
        
        # Upload Files as Assets
        $headers = @{
            "Accept" = "application/vnd.github+json"
            "Authorization" = "Bearer $token"
            "X-GitHub-Api-Version" = "2022-11-28"
            "Content-Type" = "application/octet-stream"
        }
        
        $apiUrl = "https://uploads.github.com/repos/apchevski/On-Premises-Data-Gateway-Versions/releases/$releaseId/assets?name=$standardFileName"
        Invoke-WebRequest -Uri $apiUrl -Method Post -Headers $headers -InFile "$standardFileName"

        $apiUrl = "https://uploads.github.com/repos/apchevski/On-Premises-Data-Gateway-Versions/releases/$releaseId/assets?name=$personalFileName"
        Invoke-WebRequest -Uri $apiUrl -Method Post -Headers $headers -InFile "$personalFileName"
